---

- hosts: "{{ splunkhosts }}"
  become: yes
  become_method: sudo
  tasks:
    - name: add splunk group
      group:
        name: splunk
        state: present

    - name: Add the splunk user
      user:
        name: splunk
        comment: splunk user
        group: splunk
        state: present

    - name: check if /opt/splunkforwarder directory exists
      stat: path=/opt/splunkforwarder
      register: splunkpath
    - name: Copy Archives
      unarchive:
        src: "{{ splunkfile }}"
        dest: /opt
        owner: splunk
        group: splunk
        mode: 0750
      when: not splunkpath.stat.exists
    - name: Copy passwd file
      copy:
        src: /data/Splunk_Software/passwd
        dest: /opt/splunkforwarder/etc
        owner: splunk
        group: splunk
        mode: 0700
      when: not splunkpath.stat.exists
    - name: Stop Splunk
      command: /opt/splunkforwarder/bin/splunk stop --answer-yes --no-prompt --accept-license
      become_user: splunk
    - name: Start Splunk
      command: /opt/splunkforwarder/bin/splunk start --answer-yes --no-prompt --accept-license
      become_user: splunk
